include current-theme.conf


font_family JetBrainsMono Nerd Font

# font_family Iosevka Nerd Font
# font_family      MesloLGS NF
# font_family      JetBrainsMono NFMbold_font			
italic_font 		auto
bold_italic_font    auto 
shell_integration no-cursor
shell  /usr/bin/bash --login
