[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class ghostty-dropterm"
lazy = true
window_class = "-dropterm"
position = "17% 6%"
size = "65% 60%"
offset = "200%"

[scratchpads.music]
animation = "fromBottom"
command = "kitty --class ghostty-pulsemixer -e pulsemixer"
window_class = "ghostty-pulsemixer"
size = "50% 20%"
offset = "200%"

[scratchpads.taskbar]
animation = "fromLeft"
command = "kitty --class ghostty-taskbar -e btop"
window_class = "ghostty-taskbar"
size = "30% 80%"
offset = "200%"


[scratchpads.wifi]
animation = "fromTop"
command = "kitty --class wifi -e nmtui"
window_class = "wifi"
size = "60% 20%"
offset = "200%"

[scratchpads.bluetooth]
animation = "fromTop"
command = "kitty --class bluetooth -e bluetuith"
window_class = "bluetooth"
size = "60% 20%"
offset = "200%"
